GET http://localhost:5000/

###
GET http://localhost:5000/user/allusers

###
GET http://localhost:5000/user/allposts
###

GET http://localhost:5000/user/61f960bed900fe7a05822252

###
GET http://localhost:5000/user/username/testuser01

###
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username" : "testuser02",
    "password" : "harsh123"
}

###
POST http://localhost:5000/user/update/about/61f960bed900fe7a05822252
Content-Type: application/json

{
    "fullname" : "Harsh Anand",
    "email" : "harshanand.1379@gmail.com",
    "contact" : "7562820769",
    "description": "I'm a good boy and i love to play too much."
}

###
POST http://localhost:5000/user/update/posts/61f960bed900fe7a05822252
Content-Type: application/json

{
    "post" : "https://images.unsplash.com/photo-1541963463532-d68292c34b19?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max"   
}

###
POST http://localhost:5000/user/update/photo/61f960bed900fe7a05822252
Content-Type: application/json

{
    "photo" : "https://images.unsplash.com/photo-1541963463532-d68292c34b19?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max"
}